# Generated by Django 5.2.4 on 2025-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='영화 제목')),
                ('director', models.CharField(max_length=50, verbose_name='감독')),
                ('main_actor', models.CharField(max_length=50, verbose_name='주연')),
                ('genre', models.CharField(max_length=30, verbose_name='장르')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='별점')),
                ('running_time', models.PositiveIntegerField(verbose_name='러닝타임(분)')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
    ]
