# Generated by Django 5.2.4 on 2025-07-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='장르명')),
            ],
            options={
                'verbose_name': '장르',
                'verbose_name_plural': '장르들',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='genre',
        ),
        migrations.AddField(
            model_name='review',
            name='genre',
            field=models.ManyToManyField(to='review.genre', verbose_name='장르'),
        ),
    ]
