# Generated by Django 5.2.4 on 2025-07-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_genre_remove_review_genre_review_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.PositiveIntegerField(default=2024, verbose_name='개봉연도'),
            preserve_default=False,
        ),
    ]
