# Generated by Django 5.2.4 on 2025-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.PositiveIntegerField(default=2024, verbose_name='개봉연도'),
        ),
    ]
