# Generated by Django 5.2.4 on 2025-07-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='개봉연도'),
        ),
    ]
